import os
from PIL import Image
from dotenv import load_dotenv
from google import genai
from google.genai.errors import APIError
from flask import Flask, request, jsonify, send_from_directory
from flask_cors import CORS
import markdown
from datetime import datetime

# 1. Load variables from .env file FIRST
load_dotenv()

# We specify 'dist' as the static folder for the production React build
app = Flask(__name__, static_folder='dist', static_url_path='/')
CORS(app) # Allow Vite dev server to communicate with Flask during development

# 2. Get API key cleanly
api_key_val = os.getenv("GOOGLE_API_KEY") or os.getenv("GEMINI_API_KEY")
client = genai.Client(api_key=api_key_val)

# Free Tier Active Frontier Model
MODEL_NAME = 'gemini-3.1-flash-lite'

IMAGE_PROMPT = '''
You are analyzing an uploaded image for a medical description tool.

Step 1: On the first line, reply with exactly "VALID" if this image shows medical content
(e.g. an X-ray, scan, skin condition, wound, medication, or similar clinical subject),
or exactly "INVALID" if it does not (e.g. random photos, objects, people, screenshots unrelated to medicine).

Step 2: If and only if you replied "VALID", continue on the following lines with:
- A very detailed medical description of the image.
- Any relevant medical conditions, anomalies, or abnormalities present.
- Potential treatments or recommended actions based on the observed features.
- Ensure the content is accurate and clinically relevant. Do not provide false or misleading information.

If you replied "INVALID", do not add anything else after that line.
'''

def gen_image(prompt, image):
    """Sends optimized prompt + image payloads to the active Gemini endpoint."""
    try:
        response = client.models.generate_content(
            model=MODEL_NAME,
            contents=[image, prompt]
        )
        return response.text
    except APIError as ae:
        if ae.code == 429:
            return "RATE_LIMIT_ERROR"
        return f"API_ERROR: {str(ae.message if hasattr(ae, 'message') else ae)}"
    except Exception as e:
        return f"API_ERROR: {str(e)}"

@app.route('/api/status', methods=['GET'])
def get_status():
    """Returns the backend and AI status indicators."""
    has_api_key = bool(os.getenv("GOOGLE_API_KEY") or os.getenv("GEMINI_API_KEY"))
    return jsonify({
        "status": "healthy",
        "gemini_status": "connected" if has_api_key else "disconnected",
        "model": MODEL_NAME,
        "version": "1.0.0",
        "timestamp": datetime.utcnow().isoformat() + "Z"
    })

@app.route('/api/analyze', methods=['POST'])
def analyze():
    """REST API endpoint for medical image analysis."""
    uploaded_file = request.files.get('file')
    if not uploaded_file or uploaded_file.filename == '':
        return jsonify({"error": "Please choose an image file."}), 400

    try:
        image = Image.open(uploaded_file)
        # Downsize locally to save Free Tier bandwidth
        image.thumbnail((800, 800))
    except Exception:
        return jsonify({"error": "Could not read the uploaded file as an image."}), 400

    raw = gen_image(IMAGE_PROMPT, image)

    if raw == "RATE_LIMIT_ERROR":
        return jsonify({
            "error": "Free tier rate-limit hit. Please wait 30 seconds and try submitting again."
        }), 429
    
    if raw.startswith("API_ERROR"):
        error_details = raw.replace("API_ERROR:", "").strip()
        return jsonify({
            "error": f"AI Connection Error: {error_details}"
        }), 500

    stripped = raw.strip()
    if stripped.upper().startswith("VALID"):
        # Clean up the output string, separating the "VALID" prefix tag
        parts = stripped.split("\n", 1)
        response_text = parts[1].strip() if len(parts) > 1 else stripped
        
        # Standard disclaimer
        disclaimer = (
            "This report is generated by an artificial intelligence model using Google Gemini. "
            "It is intended for informational and educational purposes only and should not be used "
            "as a primary diagnosis or as a substitute for professional clinical judgment, advice, or treatment."
        )
        
        formatted_html = markdown.markdown(response_text)
        
        return jsonify({
            "valid": True,
            "raw_response": response_text,
            "response_html": formatted_html,
            "disclaimer": disclaimer,
            "model_used": MODEL_NAME,
            "timestamp": datetime.utcnow().isoformat() + "Z"
        })
    else:
        return jsonify({
            "valid": False,
            "error": "Please provide a valid medical image.",
            "raw_response": stripped
        }), 200

# Catch-all route to serve the React application's index.html or other static files in production
@app.route('/', defaults={'path': ''})
@app.route('/<path:path>')
def catch_all(path):
    if path.startswith("api/"):
        return jsonify({"error": "Not Found"}), 404
        
    # Serve from the static folder ('dist/') if static_folder path is set
    if app.static_folder and os.path.exists(os.path.join(app.static_folder, path)):
        return send_from_directory(app.static_folder, path)
    else:
        # Default fallback to client app
        if app.static_folder and os.path.exists(os.path.join(app.static_folder, 'index.html')):
            return send_from_directory(app.static_folder, 'index.html')
        else:
            return "React Build not found. Run 'npm run build' to generate static assets in 'dist/'.", 404

if __name__ == '__main__':
    app.run(debug=True, port=5000)